#!/usr/bin/env python3
"""Generate the C interrupt map from the shell RTL that defines it.

The numbering of PLIC sources and contexts is a property of the SoC shell: which
device is wired to which line is decided where the wires are, in the selected
`soc` component. Every software tree needs the same numbering, and until this
existed each one carried its own copy -- so reordering the shell's wiring left
the bare-metal runtime and aXos silently pointing at the wrong device, with
nothing to catch it but a confusing test failure.

So the shell declares the map once, as localparams, and this derives the header
from them. Adding a device is then an edit to one file.

The declaration this parses looks like:

    localparam int unsigned PLIC_SRC_UART = 1;
    localparam int unsigned PLIC_SRC_ROLE = 2;
    localparam int unsigned PLIC_SOURCES  = 2;
    localparam int unsigned PLIC_CTX_M    = 0;
    localparam int unsigned PLIC_CTX_S    = 1;
    localparam int unsigned PLIC_CONTEXTS = 2;

Consistency is checked rather than assumed: source ids must be exactly
1..PLIC_SOURCES and context ids exactly 0..PLIC_CONTEXTS-1, each used once. That
is what catches the realistic mistake of adding a source and forgetting to bump
the count -- the build fails here, naming the problem, instead of producing a
PLIC whose top source is silently unreachable.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# `localparam int unsigned NAME = VALUE;` with flexible spacing. Anchored to the
# PLIC_ prefix so unrelated shell localparams are ignored.
DECL = re.compile(
    r"^\s*localparam\s+int\s+unsigned\s+(PLIC_[A-Z0-9_]+)\s*=\s*(\d+)\s*;",
    re.MULTILINE,
)


class MapError(Exception):
    """A malformed or self-inconsistent declaration in the shell RTL."""


def parse(text: str, origin: str) -> dict:
    found = {name: int(value) for name, value in DECL.findall(text)}
    sources = {n[len("PLIC_SRC_"):]: v
               for n, v in found.items() if n.startswith("PLIC_SRC_")}
    contexts = {n[len("PLIC_CTX_"):]: v
                for n, v in found.items() if n.startswith("PLIC_CTX_")}

    if not sources:
        raise MapError(
            f"{origin}: no `localparam int unsigned PLIC_SRC_<NAME> = <id>;` "
            "declarations found. A shell that instantiates a PLIC must declare "
            "its interrupt map; see components/soc/reference/soc_top.sv.")

    n_sources = found.get("PLIC_SOURCES")
    n_contexts = found.get("PLIC_CONTEXTS")
    if n_sources is None:
        raise MapError(f"{origin}: PLIC_SOURCES is not declared")
    if n_contexts is None:
        raise MapError(f"{origin}: PLIC_CONTEXTS is not declared")

    # Source id 0 is reserved by the PLIC spec to mean "no interrupt", so the
    # ids must cover 1..n exactly.
    expected_sources = set(range(1, n_sources + 1))
    if sorted(sources.values()) != sorted(expected_sources):
        raise MapError(
            f"{origin}: source ids {sorted(sources.values())} do not cover "
            f"1..{n_sources} exactly. Either a PLIC_SRC_* id is duplicated or "
            "out of range, or PLIC_SOURCES does not match the number declared.")

    expected_contexts = set(range(n_contexts))
    if sorted(contexts.values()) != sorted(expected_contexts):
        raise MapError(
            f"{origin}: context ids {sorted(contexts.values())} do not cover "
            f"0..{n_contexts - 1} exactly. Either a PLIC_CTX_* id is duplicated "
            "or out of range, or PLIC_CONTEXTS does not match.")

    return {"sources": sources, "contexts": contexts,
            "n_sources": n_sources, "n_contexts": n_contexts}


def render(mapping: dict, origin: str) -> str:
    lines = [
        "/* Generated by tools/gen_irq_map.py -- do not edit.",
        f" * Derived from {origin}, which is where the shell's interrupt",
        " * numbering is declared. Change it there and rebuild. */",
        "#pragma once",
        "",
        "/* Sources are numbered from 1; id 0 means \"no interrupt\". */",
        f"#define AX_PLIC_SOURCES {mapping['n_sources']}u",
    ]
    for name, value in sorted(mapping["sources"].items(), key=lambda kv: kv[1]):
        lines.append(f"#define AX_PLIC_SRC_{name} {value}u")
    lines += [
        "",
        "/* Delivery targets. Each drives one core interrupt input. */",
        f"#define AX_PLIC_CONTEXTS {mapping['n_contexts']}u",
    ]
    for name, value in sorted(mapping["contexts"].items(), key=lambda kv: kv[1]):
        lines.append(f"#define AX_PLIC_CTX_{name} {value}u")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc", required=True,
                        help="SoC shell source declaring the interrupt map")
    parser.add_argument("--output", required=True, help="header to write")
    args = parser.parse_args()

    soc = Path(args.soc)
    try:
        mapping = parse(soc.read_text(), soc.name)
    except OSError as error:
        sys.stderr.write(f"gen_irq_map: cannot read {soc}: {error}\n")
        return 1
    except MapError as error:
        sys.stderr.write(f"gen_irq_map: {error}\n")
        return 1

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    rendered = render(mapping, soc.name)
    # Only rewrite on change, so an unchanged map does not retrigger every
    # dependent compile.
    if not output.exists() or output.read_text() != rendered:
        output.write_text(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
